### PR TITLE
Initialize ExpansionConfig::trace_mac to false

### LINKED ISSUE #198: rust-bindgen fails to compile on nightly because missing trace_mac field
Hi there,

I guess the PR https://github.com/rust-lang/rust/pull/24430 broke `rust-bindgen` as it introduced a new field in the `ExpansionConfig` struct.

```
   Compiling rust-bindgen v0.13.0 (file:///Users/andreabedini/code/rust-bindgen)
src/gen.rs:118:15: 122:6 error: missing field: `trace_mac` [E0063]
src/gen.rs:118     let cfg = ExpansionConfig {
src/gen.rs:119         crate_name: "xxx".to_string(),
src/gen.rs:120         features: Some(&features),
src/gen.rs:121         recursion_limit: 64,
src/gen.rs:122     };
error: aborting due to previous error
Could not compile `rust-bindgen`.

To learn more, run the command again with --verbose.
```

Perhaps the field can be initialised to false?

### PR DESCRIPTION
**Pull request by andreabedini**
closes #198

### CODE REVIEW

**Comment by andreabedini** [comment]
ops, this is duplicate of #199

**Comment by posborne** [comment]
Nice to see we ended up on the same change at least.

**Comment by andreabedini** [comment]
:+1:

**Comment by cosmo0920** [comment]
Hi there, what is this PR status?
I've hit this problem at https://github.com/rust-lang/rust/commit/a40261ac91dd80b21830cc94de6132744e0c5078.

**Comment by crabtw** [comment]
Fixed, thanks

**Comment by cosmo0920** [comment]
Great! thanks.

**Pull request closed without merging**
