### PR TITLE
[travis] Fix build (#357)

### PR DESCRIPTION
**Pull request by KyleMayes**
This should hopefully fix the Travis CI builds, though it might take me more than one try.

---
This change is [Reviewable](https://reviewable.io/reviews/crabtw/rust-bindgen/367)

### CODE REVIEW

**Comment by Yamakaky** [comment]
Thanks, but why did you remove the matrix part? Now, it's more redundant.

**Comment by KyleMayes** [comment]
I can probably improve it, I just want to get it working first, then I'll see about simplifying it.

**Comment by KyleMayes** [comment]
Well most of the builds are compiling and running the tests successfully now, but either `cache: cargo` or `./scripts/travis-doc-upload.sh` is causing the builds to report as failed.

**Comment by Yamakaky** [comment]
Strange...

**Comment by KyleMayes** [comment]
Well the stable tests are passing now, but two of the nightly builds are failing due to failed tests.

**Comment by Yamakaky** [comment]
Any idea why the cache and doc upload fails ?

**Comment by KyleMayes** [comment]
No idea, it wasn't reporting any errors, just saying the build failed. I'll add `cache: cargo` back to see which was the culprit.

**Comment by KyleMayes** [comment]
The caching was causing the OS X builds to fail.

**Comment by Yamakaky** [comment]
Well, strange, but thanks!

**Pull request merged**
