### PR TITLE
Add option to not write attributes to the generate module

### PR DESCRIPTION
**Pull request by Twinklebear**
As mentioned in #359 defaulting to writing the `#[allow(...)]` attributes at the top of the module makes it so that the code can't be compiled into existing modules via `include!` making it hard to use bindgen for build scripts that compile some native library and generate bindings for it which are then included via:

```rust
include!(concat!(env!("OUT_DIR"), "/", "libname_bindings.rs"));
```

I think having the attributes set by default makes sense but for using bindgen in a build script, where you'd set the attributes yourself above the include, having no way to disable them makes it a pain. I'm not sure if there's other stuff that would make sense here, it could be included as a regular Rust module but I don't think a build script should write to `src/` and `include!` seems to be the recommended way to do it in the Cargo guide on build scripts.

Let me know what you think, I would find it extremely useful for my own project [ispc-rs](https://github.com/Twinklebear/ispc-rs), without this option I'm basically stuck on 0.17.0 or must resort to patching the bindgen generated modules afterwards.

---
This change is [Reviewable](https://reviewable.io/reviews/crabtw/rust-bindgen/368)

### CODE REVIEW

**Comment by Yamakaky** [comment]
Instead of removing these attributes, maybe we  should instead add an option to generate a module around the generated code?

**Comment by Twinklebear** [comment]
Tested by editing the bindgen output and this will work as well. I'll push some commits to implement this and let me know which you'd prefer to keep and merge.

**Comment by Yamakaky** [comment]
In fact, did you try something like this:
```rust
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/", "libname_bindings.rs"));
}
```

**Comment by Twinklebear** [comment]
Actually having the `include!` inside a modern is what produces the complies errors in #359 , it's odd that producing the same code but putting the mod inside the include instead of outside would work. Maybe it's a bug in how `include!` handles things? As far as I understood I thought it was just a straight C-style include that puts the raw file contents in there.

**Comment by Yamakaky** [comment]
Well, since https://play.rust-lang.org/?code=mod%20ffi%20%7B%0A%2F*%20automatically%20generated%20by%20rust-bindgen%20*%2F%0A%0A%23!%5Ballow(dead_code%2C%0A%20%20%20%20%20%20%20%20%20non_camel_case_types%2C%0A%20%20%20%20%20%20%20%20%20non_upper_case_globals%2C%0A%20%20%20%20%20%20%20%20%20non_snake_case)%5D%0A%23%5Bderive(Copy%2C%20Clone)%5D%0A%23%5Brepr(u32)%5D%0A%23%5Bderive(Debug)%5D%0Apub%20enum%20CaffePhase%20%7B%20CAFFE_TRAIN%20%3D%200%2C%20CAFFE_TEST%20%3D%201%2C%20%7D%0A%23%5Bderive(Copy%2C%20Clone)%5D%0A%23%5Brepr(u32)%5D%0A%23%5Bderive(Debug)%5D%0Apub%20enum%20CaffeMode%20%7B%20CAFFE_CPU%20%3D%200%2C%20CAFFE_GPU%20%3D%201%2C%20%7D%0Apub%20enum%20CaffeNet%20%7B%20%7D%0Apub%20enum%20CaffeBlob%20%7B%20%7D%0A%7D%0Afn%20main()%7B%7D&version=stable&backtrace=0 works, it seems to be a problem with include

**Comment by Twinklebear** [comment]
I think so as well, I'll have to look into include some maybe a bug is open for it. Since it's not a bingen issue though, I'm going to close this PR.

**Comment by Twinklebear** [comment]
Small update for anyone else running into this, it looks like a known issue with `include!`: https://github.com/rust-lang/rfcs/issues/752

**Comment by jdub** [comment]
It might be worth adding this option to bindgen since rust-lang/rfcs#752 hasn't seen activity since early 2015.

**Comment by Yamakaky** [comment]
Twinklebear just added https://github.com/Yamakaky/rust-bindgen#using-a-build-script-to-generate-bindings-at-compile-time. Is it sufficient?

**Pull request closed without merging**
