### PR TITLE
Use the correct paths for libclang on FreeBSD.

### PR DESCRIPTION
**Pull request by freqlabs**
This allows rust-bindgen to build on FreeBSD.

---
This change is [Reviewable](https://reviewable.io/reviews/crabtw/rust-bindgen/308)

### CODE REVIEW

**Comment by Yamakaky** [comment]
All packages are installed in `/usr/local` on freebsd?

**Comment by Yamakaky** [comment]
Also, check if freebsd can be added to travis.

**Comment by freqlabs** [comment]
FreeBSD installs packages in `/usr/local`. It doesn't look like Travis supports FreeBSD, sadly.

**Comment by Yamakaky** [comment]
Could you reopen you PR for https://github.com/KyleMayes/clang-sys since it's what bindgen will use in a near future?
Check also https://github.com/KyleMayes/clang-sys/issues/2.

**Pull request closed without merging**
