### PR TITLE
Improve generation of typedef types.

### LINKED ISSUE #169: Use typedef name instead of unnamed struct name
Unnamed struct + typedef:

```c
typedef struct {
…
} foo;
```

is currently translated quite literally to:

```rust
pub struct Struct_Unnamed1 {
…
}
pub type foo = Struct_Unnamed1;
```

I think it would be more elegant to use name from the typedef as struct name and translate it as:

```rust
struct foo {
…
}
```

### PR DESCRIPTION
**Pull request by Yamakaky**
Fixes #169.

---
This change is [Reviewable](https://reviewable.io/reviews/crabtw/rust-bindgen/339)

### CODE REVIEW

**Comment by Yamakaky** [comment]
I kept Struct_ and Enum_ prefixes for UnnamedX.

**Comment by crumblingstatue** [comment]
This generates erroneous code for opaque typedefed structs:

```C
typedef struct sfClock sfClock;
typedef struct sfMutex sfMutex;
typedef struct sfThread sfThread;

```

turns into

```Rust
/* automatically generated by rust-bindgen */

#![allow(dead_code, non_camel_case_types, non_snake_case)]
pub enum sfClock { }
pub type sfClock = sfClock;
pub enum sfMutex { }
pub type sfMutex = sfMutex;
pub enum sfThread { }
pub type sfThread = sfThread;

```

rustc complains because of redefinitions:
```
error: a type named `sfClock` has already been defined in this module [--explain E0428]
 --> test.rs:5:1
4 |> pub enum sfClock { }
  |> -------------------- previous definition of `sfClock` here
5 |> pub type sfClock = sfClock;
  |> ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: a type named `sfMutex` has already been defined in this module [--explain E0428]
 --> test.rs:7:1
6 |> pub enum sfMutex { }
  |> -------------------- previous definition of `sfMutex` here
7 |> pub type sfMutex = sfMutex;
  |> ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: a type named `sfThread` has already been defined in this module [--explain E0428]
 --> test.rs:9:1
8 |> pub enum sfThread { }
  |> --------------------- previous definition of `sfThread` here
9 |> pub type sfThread = sfThread;
  |> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by Yamakaky** [comment]
Done.

**Comment by Yamakaky** [comment]
BTW, do you use csfml?

**Comment by Yamakaky** [comment]
I tried to run bindgen + rustc on all the .h in csfml, it seems ok

**Comment by crumblingstatue** [comment]
Yes, it works now!



> BTW, do you use csfml?

Yes, that's what I want to generate the bindings for.

**Pull request closed without merging**
