### PR TITLE
define size_t and co in function of isize/usize in generated bindings

### PR DESCRIPTION
**Pull request by japaric**
This is consistent with how libc 0.2 is defining these types.

See the second paragraph of [1] and the discussion in [2] for rationale.

This is a [breaking-change] because re-generating bindings after this change
will change the type signatures of some functions and structs.

[1] https://github.com/rust-lang/rfcs/blob/master/text/1291-promote-libc.md#changes-from-today
[2] https://github.com/rust-lang/rust/pull/28096

---
This change is [Reviewable](https://reviewable.io/reviews/crabtw/rust-bindgen/256)

### CODE REVIEW

**Comment by Yamakaky** [comment]
Please rebase to get the latest travis.yml.

**Comment by japaric** [comment]
> Please rebase to get the latest travis.yml.

Rebased

**Comment by Yamakaky** [comment]
SGTM @nox. Maybe we should increment the version to 0.17?
In fact, I think we should put a http://keepachangelog.com/ in the repo. Github releases stopped at 0.12.

**Comment by Yamakaky** [comment]
In fact, it's strange you didn't have to change the tests ^^
Maybe we could add some for this use case?

**Comment by japaric** [comment]
Added a test.

**Comment by nox** [comment]
Why should we bind them at all actually? Why not directly use `isize` and `usize`?

**Comment by japaric** [comment]
> Why should we bind them at all actually?

AFAICT, that's what `bindgen` does with all the foreign primitive types it encounters; it always generates type aliases. I'm just going with the flow in this PR :smile:.

> Why not directly use isize and usize?

Would that make the implementation simpler? Or is the goal making the bindings easier to read for the user? I certainly prefer type aliases because it makes the signatures of functions and structs match the signatures of the C API -- at least when I'm already familiar with the C API.

**Comment by Yamakaky** [comment]
In fact, you could do the same for int8_t and co.

**Comment by japaric** [comment]
> In fact, you could do the same for int8_t and co.

I'd be in favor of this. Mainly because it reduces the amount of `std::os::raw` in the generated bindings.

**Comment by japaric** [comment]
> In fact, you could do the same for int8_t and co.

Pushed a new commit with this addition.

**Comment by Yamakaky** [comment]
SGTM. @nox?

---

Reviewed 7 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/crabtw/rust-bindgen/256#-:-KH-BSsB6XgVKM2KNv1C:1617923972)*

**Comment by Yamakaky** [comment]
Please rebase and update the changelog.

**Comment by Yamakaky** [comment]
Closing for https://github.com/crabtw/rust-bindgen/commit/5bd5ccf4a8c43a650943272e1ed9cb06f42862ca. Thank you!

**Pull request closed without merging**
