### PR TITLE
Some enum and build fixes

### PR DESCRIPTION
**Pull request by nox**
* Makes build.rs not run again when the build is fresh.
 * Makes it support long long enums.
 * Fixes the bug in #232.

### CODE REVIEW

**Comment by nox** [comment]
@dimbleby Addressed your comments.

**Comment by dimbleby** [comment]
That was quick!  Thanks.

I notice that there'll be a small conflict between this and my #265 (because `UnsuffixedIntLit` doesn't carry its sign around with it any more) so one of us will have to do a little more work if they're both to go through.

**Comment by dimbleby** [comment]
Actually, that makes me realise: I had to make changes for `UnsuffixedIntLit` in two places, the other being `const_to_rs`.

Should this fix also be making an analogous change in the treatment of constants?

**Comment by nox** [comment]
Will take a look.

**Comment by Yamakaky** [comment]
Seems good to me. @nox ?

**Comment by nox** [comment]
Rebasing it with the syntex update, and adding the no-enum flag.

**Comment by nox** [comment]
Of course the syntex upgrade broke everything. ;)

**Comment by nox** [comment]
@Yamakaky Damn it… There are currently no options during the codegen itself, only during parsing… :(

**Comment by Yamakaky** [comment]
That what I saw, I wanted to add a switch to use libc instead of std::os::raw...

**Comment by nox** [comment]
Merging now because it would be silly to block this for that options thing.

Feel free to recommit the univariant thing, I thought adding the option would be simple but it isn't. :(

**Pull request merged**
