### PR TITLE
Add #[derive(Debug)] to all structs and enums.

### LINKED ISSUE #261: Derive Debug for items
It would be useful if the generated file includes struct derived "Debug" for items
`#[derive(Debug)]`
I do not see much downside in it, and we can make this optional if there is.

### PR DESCRIPTION
**Pull request by Yamakaky**
The function name isn't accurate now, maybe it should be changed?

Fixes #261

### CODE REVIEW

**Comment by nox** [comment]
@Yamakaky Rather, I think it should go into another function.

**Comment by Yamakaky** [comment]
In fact, as pointed by #261, derive(Debug) will fail if there is a big array as member. Is there a mean to check if deriving is possible for a struct?

**Comment by nox** [comment]
No, but it should be possible to check whether the struct contains an array which is larger than 32 items.

**Comment by Yamakaky** [comment]
Done! (but not tested)

**Comment by Yamakaky** [comment]
The build fails, but it doesn't seem related to my changes.

**Comment by WiSaGaN** [comment]
Nice work. Can it be merged?

**Comment by nox** [comment]
@WiSaGaN We aren't maintainers. :(

**Comment by nox** [comment]
@Yamakaky I don't think your code accounts for structs using structs that use large arrays.

**Comment by Yamakaky** [comment]
You are right. WIP ^^

**Comment by Yamakaky** [comment]
Done!

**Comment by Yamakaky** [comment]
@nox Seems good?

**Comment by nox** [comment]
LGTM.

**Pull request closed without merging**
