### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by dimbleby**
Updating dependencies - in particular, syntex_syntax.

### CODE REVIEW

**Comment by Yamakaky** [comment]
May you rebase your commits in one commit please?

**Comment by dimbleby** [comment]
Done

**Comment by nox** [comment]
I'm pretty sure this broke master.

**Comment by nox** [comment]
Ah no, it's the univariant thing.

**Comment by Yamakaky** [comment]
Fixed. I didn't see it because the CI of the univariant was not rerun after merge of this PR.

**Comment by nox** [comment]
Reverted the commit. I'll do the enum-disabling flag right now so that the whole situation is fixed.

**Pull request merged**
