### PR TITLE
Introduce -no-rust-enums (fixes #276)

### LINKED ISSUE #276: Make generation of C enums as Rust enums optional

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by Yamakaky** [comment]
On it ;)

**Comment by Yamakaky** [comment]
I'm thinking: while we are on cmdline arguments, maybe we could us https://github.com/docopt/docopt.rs?

**Comment by Yamakaky** [comment]
Seems good to me.

**Comment by nox** [comment]
Feel free to improve the CLI interface btw!

**Pull request merged**
