### PR TITLE
produce valid univariant enums

### LINKED ISSUE #255: error: unsupported representation for univariant enum
Given a header file contains a single variant enum:

``` C
// snip from /usr/include/cuda.h
typedef enum CUipcMem_flags_enum {
    CU_IPC_MEM_LAZY_ENABLE_PEER_ACCESS = 0x1 /**< Automatically enable peer access between remote devices as needed */
} CUipcMem_flags;
```

bindgen produces a non-compilable module:

``` rust
/* automatically generated by rust-bindgen */

#[derive(Clone, Copy)]
#[repr(u32)]
pub enum Enum_CUipcMem_flags_enum { CU_IPC_MEM_LAZY_ENABLE_PEER_ACCESS = 1, }
pub type CUipcMem_flags = Enum_CUipcMem_flags_enum;
```

That errors with:

``` rust
test.rs:5:1: 5:78 error: unsupported representation for univariant enum [E0083]
test.rs:5 pub enum Enum_CUipcMem_flags_enum { CU_IPC_MEM_LAZY_ENABLE_PEER_ACCESS = 1, }
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test.rs:5:1: 5:78 help: run `rustc --explain E0083` to see a detailed explanation
error: aborting due to previous error
```

---

A possible solution to make bindgen generate a valid module in this case, is to follow the recommendation of `rustc --explain E0083`:

```
At present, it's not possible to define a custom representation for an enum with
a single variant. As a workaround you can add a `Dummy` variant.

See: https://github.com/rust-lang/rust/issues/10292
```

And have bindgen add a `__DUMMY` variant to the translated single-variant enum.

Does that sound like a reasonable solution?

cc @nox

### PR DESCRIPTION
**Pull request by japaric**
Instead of generating a enum like this:

``` rust
pub enum Enum_CUipcMem_flags_enum {
    CU_IPC_MEM_LAZY_ENABLE_PEER_ACCESS = 1,
}
```

Which is a compiler error because repr can't be used with univariant enums.
See https://github.com/rust-lang/rust/issues/10292

We generate a two variant enum with a dummy variant.

``` rust
pub enum Enum_CUipcMem_flags_enum {
    CU_IPC_MEM_LAZY_ENABLE_PEER_ACCESS = 1,
    __DUMMY,
}
```

Which is the recommend workaround to the previous compiler error.

closes #255

### CODE REVIEW

**Comment by japaric** [comment]
rust-lang/rust#10292 may be fixed in rust-lang/rust#31232. So, in the future, we can add a flag to BindgenOptions to disable the generation of this dummy variant.

**Comment by Yamakaky** [comment]
Cherry-picked https://github.com/crabtw/rust-bindgen/commit/fa6f4407f3cd366c2390b390a6400db8a5c5a071

**Comment by nox** [comment]
@Yamakaky Please do a PR next time, this broke master.

**Comment by nox** [comment]
Superseded by #280.

**Pull request closed without merging**
