### PR TITLE
Fixes build after Rust's elimination of boxed closures.

### PR DESCRIPTION
**Pull request by chris-chambers**
*Note: This PR now includes everything from #154, #155 and #157.*

### CODE REVIEW

**Comment by fbernier** [comment]
Good stuff :+1:

**Comment by aidanhs** [comment]
There's a less intrusive way of fixing the unboxed closures - https://github.com/aidanhs/rust-bindgen/commit/5a708394c05351218db32e12490840ba6a08bb0b

This means, as before, you're directly passing a pointer to the closure rather than a struct wrapper, which seems unnecessary.

**Comment by aidanhs** [comment]
You could actually get rid of all the boxes in my commit as well if you chose, since I see you've gone the route of duplicating the trait definition `FnMut(&Cursor, &Cursor) -> Enum_CXChildVisitResult` on line 21 and 63.

**Comment by chris-chambers** [comment]
@aidanhs, I was just thinking about this, actually.  I ended up with the extra struct mainly because I didn't know the exact syntax to use for the lifetimes in the `pub type =`, and I forgot to go back and figure it out before pushing up.

The tests don't build in aidanhs@5a70839.  Would you mind if I rebased this PR onto it an applied my changes that get the tests running?

**Comment by aidanhs** [comment]
Great minds - just created an alternative PR at #157.
Can you run the tests? The plugin tests don't work on my machine because of #89.

**Comment by chris-chambers** [comment]
I have the tests running.  I'm integrating on a couple of minor ideas from my branch, and I'll update this PR.

**Comment by aidanhs** [comment]
Ah, you've rebased onto my aphs-rust-nightly branch.
I'd have suggested using aphs-fix-unboxed-closures (which is the other PR, which is a reworked version of aphs-rust-nightly) instead, as I used your replacement crate/module attributes because I didn't really know what I was doing with them.

**Comment by chris-chambers** [comment]
Oh, bummer.  Let me re-rebase

**Comment by chris-chambers** [comment]
Alright, there we go.

**Comment by aidanhs** [comment]
:+1:
(as an aside, is the `for<'a>` syntax documented anywhere?)

**Comment by chris-chambers** [comment]
I think for<'a> is fairly new.  Search for "higher ranked lifetimes", maybe.

**Pull request merged**
