### PR TITLE
Cleanup some warnings from Clippy

### PR DESCRIPTION
**Pull request by mcarton**
For information, here is the [log before and after](https://gist.github.com/mcarton/fb8dc2e13b6d641b898c) with Clippy.
The remaining warning is a false positive.

### CODE REVIEW

**Comment by Manishearth** [comment]
I thought I had fixed that lifetime bug, but it may have changed. Will look into when I'm back on my laptop (mondayish).

**Comment by michaelwu** [comment]
The changes look good, but it looks like it's bitrotted a bit. Do you mind rebasing? I'll try to get this in before anything else bitrots it.

**Comment by mcarton** [comment]
@michaelwu I don’t mind at all. Done.

**Comment by michaelwu** [comment]
Thanks!

**Pull request merged**
